In [16]:
import numpy as np

In [17]:
l = ["sudh",1,2,3,4] #with the help of the list[] we create an array.

In [18]:
l

['sudh', 1, 2, 3, 4]

In [19]:
type(l)

list

In [20]:
arr = np.array(l) #converting list into an array

In [21]:
arr #create an array

array(['sudh', '1', '2', '3', '4'], dtype='<U21')

In [22]:
type(arr) #we can check the type after converting

numpy.ndarray

In [ ]:
#-------------- # -------------------------

In [23]:
t = (14,15,25,"aaditya",True) #with the help of the tuple() we can create an array.

In [24]:
t

(14, 15, 25, 'aaditya', True)

In [25]:
type(t)

tuple

In [26]:
arr1 = np.array(t)

In [27]:
arr1

array(['14', '15', '25', 'aaditya', 'True'], dtype='<U21')

In [29]:
type(arr) #we can check the type after converting

numpy.ndarray

In [ ]:
#--------------#---------------------

In [32]:
a = np.array([3,4,5,6,3.0]) #upcasting 

In [33]:
a

array([3., 4., 5., 6., 3.])

In [35]:
b = np.array(([1,2] , [3,4])) #Two dimensional array 2-D or Multidimensional array

In [36]:
b

array([[1, 2],
       [3, 4]])

In [40]:
#indexing # extracting all the values 

b[0] #0th index row data

array([1, 2])

In [41]:
b[1] #1st index row data

array([3, 4])

In [ ]:
#individuals values extract

In [43]:
b[0][0]

1

In [44]:
b[0][1]

2

In [45]:
b[1][0]

3

In [46]:
b[1][1]

4

In [54]:
c = np.array([1,2,3,4], ndmin = 5) # 5 dimnesional array

In [55]:
c

array([[[[[1, 2, 3, 4]]]]])

In [59]:
# Extracting 1

c[0][0][0][0][0] #0th index

1

In [60]:
# Extracting 2

c[0][0][0][0][1] #1st index

2

In [61]:
# 2D 
d = np.array(([1,2] , [3,4]))

In [62]:
d

array([[1, 2],
       [3, 4]])

In [65]:
# 3D
e = np.asanyarray([1,2,3,4,5]) #asanyarray

In [66]:
e

array([1, 2, 3, 4, 5])

In [67]:
f = np.asarray([1,2,3,4,5]) #asarray

In [68]:
f

array([1, 2, 3, 4, 5])

In [76]:
g = np.fromfunction(lambda i,j : i == j, (3,3)) #fromfunction # 3 * 3 array #its 2 dimensions array # == comparison operator (True,False)

In [78]:
g

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [81]:
h = np.fromfunction(lambda i, j : i == j, (4,4))

In [82]:
h

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [89]:
i = np.fromfunction(lambda i, j : i * j, (4,4)) #by default its showing floting number

In [90]:
i

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [94]:
j = np.fromfunction(lambda i, j : i * j, (4,4), dtype=int) #converting into an integer

In [96]:
j

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [102]:
k = np.fromfunction(lambda i, j, z : i*j*z ,(3,3,3), dtype=int) #3D array

In [104]:
k  #3 array, 3 Rows, 3 columns (3,3,3) 3 * 3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [113]:
l = np.fromfunction(lambda i, j, z : i*j*z ,(3,3,2), dtype=int) #3D array

In [115]:
l #3 array , 3 Rows, 2 columns (3,3,2) 3 * 2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [117]:
l = np.fromfunction(lambda i, j, z : i*j*z ,(4,3,2), dtype=int) #3D array

In [118]:
l #4 array , 3 Rows, 2 columns (4,3,2) 3 * 2 

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [124]:
l1 = np.fromfunction(lambda i, j, z, p : i*j*z*p ,(4,3,2,2), dtype=int) #4D array

In [126]:
l1 # we have 2 * 2 arrays and 3 such arrays with 4 combinations

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [200]:
m = np.fromfunction(lambda i, j, z : i * j * z, (4,3,2), dtype=int)

In [201]:
m

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [203]:
m.reshape(2,6,2) #reshaping (toal number of elemnent is 24)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4],
        [0, 0],
        [0, 3],
        [0, 6]]])

In [205]:
m.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [207]:
m.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [209]:
pd.DataFrame(m.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [211]:
m.reshape(4,2,1,3) #4-D array

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [246]:
m.reshape(4,2,1,3,1) #5 - D array

array([[[[[0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0]]]],



       [[[[0],
          [0],
          [0]]],


        [[[1],
          [0],
          [2]]]],



       [[[[0],
          [0],
          [0]]],


        [[[2],
          [0],
          [4]]]],



       [[[[0],
          [0],
          [0]]],


        [[[3],
          [0],
          [6]]]]])

In [133]:
m.ndim #its 3 dimension array

3

In [137]:
m.size #total number of element in the array

24

In [139]:
m.shape 

(4, 3, 2)

In [143]:
m.dtype

dtype('int64')

In [146]:
x1 = np.fromfunction(lambda i, j : i * j, (4,4), dtype=int)

In [148]:
x1  

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [151]:
import pandas as pd
pd.DataFrame(x1)    #converting 2-D array in Dataframe

0  1  2  3
0  0  0  0  0
1  0  1  2  3
2  0  2  4  6
3  0  3  6  9

In [162]:
x2 = np.fromfunction(lambda i, j : i * j, (400,10), dtype=int) #400 - number of rows and 10 - number of columns

In [163]:
x2

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    1,    2, ...,    7,    8,    9],
       [   0,    2,    4, ...,   14,   16,   18],
       ...,
       [   0,  397,  794, ..., 2779, 3176, 3573],
       [   0,  398,  796, ..., 2786, 3184, 3582],
       [   0,  399,  798, ..., 2793, 3192, 3591]])

In [165]:
pd.DataFrame(x2) #converting 2-D array in Dataframe 

0    1    2     3     4     5     6     7     8     9
0    0    0    0     0     0     0     0     0     0     0
1    0    1    2     3     4     5     6     7     8     9
2    0    2    4     6     8    10    12    14    16    18
3    0    3    6     9    12    15    18    21    24    27
4    0    4    8    12    16    20    24    28    32    36
..  ..  ...  ...   ...   ...   ...   ...   ...   ...   ...
395  0  395  790  1185  1580  1975  2370  2765  3160  3555
396  0  396  792  1188  1584  1980  2376  2772  3168  3564
397  0  397  794  1191  1588  1985  2382  2779  3176  3573
398  0  398  796  1194  1592  1990  2388  2786  3184  3582
399  0  399  798  1197  1596  1995  2394  2793  3192  3591

[400 rows x 10 columns]

In [180]:
#random function

np.random.rand(10,4)

array([[0.35306594, 0.78148736, 0.43962204, 0.40271851],
       [0.55818887, 0.26677978, 0.52059278, 0.53563985],
       [0.21964918, 0.47617356, 0.83068587, 0.67077956],
       [0.01906683, 0.43426876, 0.87244024, 0.53070687],
       [0.40524681, 0.68573266, 0.60292193, 0.30271394],
       [0.64648017, 0.19693969, 0.22308616, 0.61360593],
       [0.96401006, 0.31923253, 0.93968052, 0.42494954],
       [0.99440739, 0.41751816, 0.97573755, 0.11940516],
       [0.03239882, 0.06696368, 0.68247978, 0.74116974],
       [0.93175988, 0.51396801, 0.14632876, 0.67336675]])

In [185]:
np.random.randint(4,50)

16

In [186]:
np.random.randn(4,5) #normally distribution number where mean = 0 and sd = 1

array([[ 1.30134253, -0.11966737,  1.25063733,  0.6590845 ,  1.34177576],
       [-0.51173628, -0.39127348,  0.25477595,  1.18682247, -1.82912542],
       [-0.86860889, -1.08606999,  0.72113265, -0.15958013, -0.21823597],
       [-0.04324759,  1.02255401, -1.40922407,  0.19788473, -1.41282752]])

In [195]:
y = pd.DataFrame(np.random.randn(4,5))

In [196]:
y

0         1         2         3         4
0 -0.059623  0.219477 -1.754264  0.816814 -0.702261
1  1.152494  0.619546  0.825694 -0.851798  0.375939
2 -0.257623  0.418795 -1.906027  0.294728 -1.371264
3 -1.304343  0.390126  1.668035  1.287778 -0.278375

In [127]:
#converting into an matrix

np.mat(np.fromfunction(lambda i, j : i * j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [84]:
#matrix

In [69]:
x = np.mat([1,2,3,4,5]) #matrix defined 2D array by default #2D array

In [70]:
x

matrix([[1, 2, 3, 4, 5]])

In [74]:
#ex.

np.asanyarray(np.mat([1,2,3,4,5])) 

matrix([[1, 2, 3, 4, 5]])

# BARTY NUMPY

In [215]:
arr = np.array([1,2,3,4,5])

In [216]:
arr

array([1, 2, 3, 4, 5])

In [219]:
np.version

<module 'numpy.version' from '/Users/aadityakamble/opt/anaconda3/lib/python3.9/site-packages/numpy/version.py'>

In [220]:
type(arr)

numpy.ndarray

In [221]:
arr1 = np.array(42)

In [222]:
arr1 #0-D 

array(42)

In [223]:
arr2 = np.array([1,2,3,4,5])

In [224]:
arr2 #1-D

array([1, 2, 3, 4, 5])

In [231]:
arr3 = np.array([[1,2,3,5],[1,4,5,7]]) 

In [232]:
arr3 #2-D

array([[1, 2, 3, 5],
       [1, 4, 5, 7]])

In [233]:
arr4 = np.array([[[1,2,3],[4,5,6]]])

In [234]:
arr4 #3-D

array([[[1, 2, 3],
        [4, 5, 6]]])

In [238]:
#check number of dimnesions 
arr1.ndim

0

In [239]:
arr2.ndim

1

In [240]:
arr3.ndim

2

In [241]:
arr4.ndim

3

In [247]:
#create an array with 5 dimnesion 

arr5 = np.array([1,2,3,4,5], ndmin = 5)

In [248]:
arr5

array([[[[[1, 2, 3, 4, 5]]]]])

In [249]:
#indexing

arr6 = np.array([1,2,3,4])

In [250]:
arr6

array([1, 2, 3, 4])

In [251]:
arr6[0]

1

In [252]:
arr6[1]

2

In [253]:
arr[2] + arr[3] #addition

7

In [255]:
arr7 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [256]:
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [257]:
#you can write both the condition (indexing)
#access the element
arr7[0,1]

2

In [258]:
arr7[0][1]

2

In [259]:
arr7[0,3]

4

In [260]:
arr7[0][3]

4

In [261]:
arr7[1,4]

10

In [262]:
arr7[1][4]

10

In [263]:
#negative indexing

arr7[1,-1]

10

In [264]:
arr7[1][-1]

10

In [265]:
arr8 = np.array([1,2,3,4,5,6,7])

In [266]:
arr8

array([1, 2, 3, 4, 5, 6, 7])

In [267]:
arr8[4:]

array([5, 6, 7])

In [268]:
arr8[:4]

array([1, 2, 3, 4])

In [270]:
arr8[-3:-1]

array([5, 6])

In [272]:
arr7[1,1:4]

array([7, 8, 9])

In [280]:
arr7[0:2,2]

array([3, 8])

In [281]:
arr7[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [290]:
arr9 = np.array([[1,2,3,4],[5,6,7,8]])

In [291]:
arr9

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [292]:
type(arr9)

numpy.ndarray

In [293]:
arr9.shape

(2, 4)

In [294]:
arr9.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])